# Builds npm packages and publishes to GitHub's npm repo (https://npm.pkg.github.com).
#
# The workflow will only run if commit message contains [tag:patch|minor|major]
name: Publish Update

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 16

jobs:
  # ----------------------------------------------------
  # Build npm packages, version, and publish
  #  - runs if [tag:patch|minor|major] in commit message
  # ----------------------------------------------------
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    # only run if commit message contains versioning 'flag'
    if: |
      contains(github.event.head_commit.message, '[tag:patch]')
      || contains(github.event.head_commit.message, '[tag:minor]')
      || contains(github.event.head_commit.message, '[tag:major]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)

      # User name and email are required by lerna
      - name: Git identity
        run: |
          git config --global user.name "${{ github.actor}}"
          git config --global user.email "${{ github.actor}}@users.noreply.github.com"

      # Set node version and (more importantly) authenticate to package registry
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          scope: '@credibil'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Get semver action (patch|minor|major) from commit message
      - name: Commit semver
        id: semver
        uses: actions/github-script@v5
        with:
          script: |
            const msg = "${{ github.event.head_commit.message}}"
            const start = msg.indexOf('[tag:')
            const end = msg.indexOf(']', start)
            return msg.substring(start + 5, end)
          result-encoding: string

      # Publish to npm.pkg.github.com (using settings in each package's package.json)
      - name: Publish packages
        run: |
          npm install
          lerna publish ${{steps.semver.outputs.result}} --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

